--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.admins (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT admins_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text])))
);


ALTER TABLE public.admins OWNER TO root;

--
-- Name: admins_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumni_profiles; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.alumni_profiles (
    id bigint NOT NULL,
    avatar character varying(255),
    batch character varying(255),
    bio text,
    company character varying(255),
    connections integer,
    created_at timestamp(6) without time zone,
    department character varying(255),
    is_visible boolean,
    location character varying(255),
    name character varying(255),
    profession character varying(255),
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL
);


ALTER TABLE public.alumni_profiles OWNER TO root;

--
-- Name: alumni_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.alumni_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumni_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumni_skills; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.alumni_skills (
    alumni_id bigint NOT NULL,
    skill character varying(255)
);


ALTER TABLE public.alumni_skills OWNER TO root;

--
-- Name: announcements; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.announcements (
    id bigint NOT NULL,
    active boolean DEFAULT true NOT NULL,
    author_email character varying(100),
    author_name character varying(100),
    category character varying(50),
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    image_url character varying(500),
    is_urgent boolean DEFAULT false NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    view_count integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.announcements OWNER TO root;

--
-- Name: announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calendar_integrations; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.calendar_integrations (
    id bigint NOT NULL,
    access_token character varying(500),
    calendar_id character varying(100),
    calendar_name character varying(100) NOT NULL,
    calendar_type character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    last_sync_error character varying(500),
    last_sync_time timestamp(6) without time zone NOT NULL,
    refresh_token character varying(500),
    sync_events boolean DEFAULT false NOT NULL,
    sync_invitations boolean DEFAULT false NOT NULL,
    sync_settings character varying(500),
    token_expiry timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(50) NOT NULL,
    calendar_url character varying(500),
    sync_frequency_hours integer DEFAULT 0 NOT NULL,
    sync_from_external boolean DEFAULT false NOT NULL,
    sync_recurring_events boolean DEFAULT false NOT NULL,
    sync_reminders boolean DEFAULT false NOT NULL,
    sync_to_external boolean DEFAULT false NOT NULL,
    CONSTRAINT calendar_integrations_calendar_type_check CHECK (((calendar_type)::text = ANY ((ARRAY['GOOGLE_CALENDAR'::character varying, 'OUTLOOK_CALENDAR'::character varying, 'APPLE_CALENDAR'::character varying, 'ICAL_FEED'::character varying, 'CUSTOM'::character varying])::text[])))
);


ALTER TABLE public.calendar_integrations OWNER TO root;

--
-- Name: calendar_integrations_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.calendar_integrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_integrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: connections; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.connections (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    receiver_username character varying(255) NOT NULL,
    requester_username character varying(255) NOT NULL,
    status character varying(255),
    CONSTRAINT connections_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.connections OWNER TO root;

--
-- Name: connections_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.connections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.connections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_analytics; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.event_analytics (
    id bigint NOT NULL,
    actual_attendees integer NOT NULL,
    attendance_rate double precision NOT NULL,
    confirmed_attendees integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    declined_attendees integer NOT NULL,
    event_id bigint NOT NULL,
    last_updated timestamp(6) without time zone NOT NULL,
    maybe_attendees integer NOT NULL,
    no_shows integer NOT NULL,
    notes character varying(500),
    pending_responses integer NOT NULL,
    response_rate double precision NOT NULL,
    total_invitations integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    average_response_time_hours integer DEFAULT 0 NOT NULL,
    event_end_date timestamp(6) without time zone,
    event_start_date timestamp(6) without time zone,
    event_title character varying(50) NOT NULL,
    first_rsvp_time timestamp(6) without time zone,
    is_completed boolean DEFAULT false NOT NULL,
    last_rsvp_time timestamp(6) without time zone,
    organizer_username character varying(50) NOT NULL,
    total_comments integer DEFAULT 0 NOT NULL,
    total_media_uploads integer DEFAULT 0 NOT NULL,
    total_reminders integer DEFAULT 0 NOT NULL,
    engagement_rate double precision DEFAULT 0.0 NOT NULL
);


ALTER TABLE public.event_analytics OWNER TO root;

--
-- Name: event_analytics_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.event_analytics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_analytics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_comments; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.event_comments (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    is_edited boolean DEFAULT false NOT NULL,
    likes integer DEFAULT 0 NOT NULL,
    parent_comment_id bigint,
    replies integer DEFAULT 0 NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(50) NOT NULL
);


ALTER TABLE public.event_comments OWNER TO root;

--
-- Name: event_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.event_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_invitations; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.event_invitations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    invited_by_username character varying(50) NOT NULL,
    invited_username character varying(50) NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    is_responded boolean DEFAULT false NOT NULL,
    personal_message character varying(500),
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.event_invitations OWNER TO root;

--
-- Name: event_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.event_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_media; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.event_media (
    id bigint NOT NULL,
    caption character varying(200),
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    file_name character varying(200) NOT NULL,
    file_size bigint NOT NULL,
    file_type character varying(50) NOT NULL,
    file_url character varying(500) NOT NULL,
    is_approved boolean DEFAULT false NOT NULL,
    likes integer DEFAULT 0 NOT NULL,
    media_type character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uploaded_by_username character varying(50) NOT NULL,
    CONSTRAINT event_media_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying, 'DOCUMENT'::character varying])::text[])))
);


ALTER TABLE public.event_media OWNER TO root;

--
-- Name: event_media_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.event_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_participations; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.event_participations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    message character varying(500),
    participant_username character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT event_participations_status_check CHECK (((status)::text = ANY ((ARRAY['GOING'::character varying, 'MAYBE'::character varying, 'NOT_GOING'::character varying, 'PENDING'::character varying])::text[])))
);


ALTER TABLE public.event_participations OWNER TO root;

--
-- Name: event_participations_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.event_participations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_participations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_reminders; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.event_reminders (
    id bigint NOT NULL,
    channel character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    custom_message character varying(200),
    event_id bigint NOT NULL,
    is_active boolean DEFAULT false NOT NULL,
    is_sent boolean DEFAULT false NOT NULL,
    reminder_time timestamp(6) without time zone NOT NULL,
    reminder_type character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(50) NOT NULL,
    CONSTRAINT event_reminders_channel_check CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'SMS'::character varying, 'PUSH_NOTIFICATION'::character varying, 'IN_APP'::character varying])::text[]))),
    CONSTRAINT event_reminders_reminder_type_check CHECK (((reminder_type)::text = ANY ((ARRAY['ONE_HOUR_BEFORE'::character varying, 'ONE_DAY_BEFORE'::character varying, 'ONE_WEEK_BEFORE'::character varying, 'CUSTOM'::character varying])::text[])))
);


ALTER TABLE public.event_reminders OWNER TO root;

--
-- Name: event_reminders_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.event_reminders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_reminders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_templates; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.event_templates (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by_username character varying(50) NOT NULL,
    default_duration_minutes integer,
    default_end_time time(6) without time zone,
    default_start_time time(6) without time zone,
    description text,
    event_type character varying(50),
    invite_message character varying(500),
    is_online boolean DEFAULT false NOT NULL,
    is_public boolean DEFAULT false NOT NULL,
    is_recurring boolean DEFAULT false NOT NULL,
    location character varying(100),
    max_participants integer NOT NULL,
    meeting_link character varying(500),
    notes character varying(500),
    organizer_email character varying(100),
    organizer_name character varying(100),
    privacy character varying(20) NOT NULL,
    recurrence_days character varying(500),
    recurrence_interval integer,
    recurrence_type character varying(20),
    tags character varying(500),
    template_name character varying(200) NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    usage_count integer NOT NULL,
    category character varying(20) NOT NULL,
    default_recurrence_days character varying(100),
    default_recurrence_interval integer DEFAULT 1,
    default_recurrence_type character varying(20),
    is_active boolean DEFAULT true NOT NULL,
    name character varying(200) NOT NULL,
    supports_recurrence boolean DEFAULT false NOT NULL,
    total_ratings integer DEFAULT 0 NOT NULL,
    average_rating double precision DEFAULT 0.0 NOT NULL,
    CONSTRAINT event_templates_category_check CHECK (((category)::text = ANY (ARRAY['CONFERENCE'::text, 'WORKSHOP'::text, 'MEETING'::text, 'NETWORKING'::text, 'SEMINAR'::text, 'WEBINAR'::text, 'SOCIAL'::text, 'ACADEMIC'::text, 'PROFESSIONAL'::text, 'CAREER'::text, 'REUNION'::text, 'SPORTS'::text, 'MENTORSHIP'::text, 'OTHER'::text]))),
    CONSTRAINT event_templates_default_recurrence_type_check CHECK (((default_recurrence_type)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT event_templates_privacy_check CHECK (((privacy)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'INVITE_ONLY'::character varying])::text[]))),
    CONSTRAINT event_templates_recurrence_type_check CHECK (((recurrence_type)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying, 'YEARLY'::character varying, 'CUSTOM'::character varying])::text[])))
);


ALTER TABLE public.event_templates OWNER TO root;

--
-- Name: event_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.event_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_participants integer DEFAULT 0 NOT NULL,
    description text,
    end_date timestamp(6) without time zone NOT NULL,
    event_type character varying(50),
    is_online boolean DEFAULT false NOT NULL,
    location character varying(100),
    max_participants integer DEFAULT 0 NOT NULL,
    meeting_link character varying(500),
    organizer character varying(100),
    start_date timestamp(6) without time zone NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    organizer_email character varying(100),
    organizer_name character varying(100),
    created_by_username character varying(50),
    invite_message character varying(500),
    privacy character varying(20) DEFAULT 'PUBLIC'::character varying
);


ALTER TABLE public.events OWNER TO root;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experiences; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.experiences (
    id bigint NOT NULL,
    company character varying(255),
    description character varying(255),
    period character varying(255),
    title character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.experiences OWNER TO root;

--
-- Name: experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feature_flags; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.feature_flags (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(500),
    enabled boolean NOT NULL,
    feature_name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.feature_flags OWNER TO root;

--
-- Name: feature_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.feature_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feature_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interests; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.interests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    interest character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.interests OWNER TO root;

--
-- Name: interests_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.interests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.profiles (
    id bigint NOT NULL,
    batch character varying(10),
    bio character varying(255),
    created_at timestamp(6) without time zone,
    facebook character varying(255),
    github character varying(255),
    instagram character varying(255),
    linkedin character varying(255),
    location character varying(255),
    name character varying(255),
    phone character varying(20),
    profession character varying(255),
    skills character varying(255)[],
    twitter character varying(255),
    updated_at timestamp(6) without time zone,
    website character varying(255),
    linked_in character varying(255),
    show_linked_in boolean,
    show_phone boolean,
    show_website boolean,
    username character varying(100),
    department character varying(255),
    email character varying(255),
    show_email boolean,
    connections integer,
    show_facebook boolean,
    user_id character varying(50)
);


ALTER TABLE public.profiles OWNER TO root;

--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recurring_events; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.recurring_events (
    id bigint NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by_username character varying(50),
    current_participants integer DEFAULT 0 NOT NULL,
    description text,
    end_date timestamp(6) without time zone NOT NULL,
    event_type character varying(50),
    invite_message character varying(500),
    is_online boolean DEFAULT false NOT NULL,
    is_series boolean DEFAULT false NOT NULL,
    is_template boolean DEFAULT false NOT NULL,
    location character varying(100),
    max_participants integer NOT NULL,
    meeting_link character varying(500),
    organizer_email character varying(100),
    organizer_name character varying(100),
    parent_event_id bigint,
    privacy character varying(20) NOT NULL,
    recurrence_days character varying(100),
    recurrence_end_date timestamp(6) without time zone NOT NULL,
    recurrence_interval integer NOT NULL,
    recurrence_type character varying(20) NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    generate_instances boolean DEFAULT false NOT NULL,
    max_occurrences integer DEFAULT 0 NOT NULL,
    CONSTRAINT recurring_events_privacy_check CHECK (((privacy)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'INVITE_ONLY'::character varying])::text[]))),
    CONSTRAINT recurring_events_recurrence_type_check CHECK (((recurrence_type)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying, 'YEARLY'::character varying, 'CUSTOM'::character varying])::text[])))
);


ALTER TABLE public.recurring_events OWNER TO root;

--
-- Name: recurring_events_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.recurring_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurring_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.reports (
    id bigint NOT NULL,
    admin_notes text,
    assigned_to character varying(100),
    attachment_url character varying(500),
    category character varying(50),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    priority character varying(20),
    reporter_email character varying(100),
    reporter_name character varying(100),
    status character varying(20),
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.reports OWNER TO root;

--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255),
    username character varying(100),
    user_id character varying(50),
    active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.users OWNER TO root;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.admins (id, active, created_at, email, name, password_hash, role, updated_at) FROM stdin;
1	t	2025-07-31 01:51:12.870989	admin@ijaa.com	Administrator	$2a$12$y3fhHC5PdD5T5t2BECat4OAciXA2zhK7MS5XQLCl5l7xt.mh6KHja	ADMIN	2025-07-31 01:51:12.871015
3	t	2025-08-08 19:36:26.263214	newadmin2@ijaa.com	New Admin	$2a$12$ZldN/hDSHI1mBA/uu/.kS.fQZq72pnTzSjEnVE37/aSQ0LjhmFfiO	ADMIN	2025-08-08 19:36:26.263221
2	f	2025-08-03 11:10:12.407424	newadmin@ijaa.com	New Admin	$2a$12$cSelKrFkAWh7fQe2/52fZeLiMnV9iV75dYZTB1xCzUiECEIFzSWau	ADMIN	2025-08-08 19:57:03.398123
\.


--
-- Data for Name: alumni_profiles; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.alumni_profiles (id, avatar, batch, bio, company, connections, created_at, department, is_visible, location, name, profession, updated_at, username) FROM stdin;
\.


--
-- Data for Name: alumni_skills; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.alumni_skills (alumni_id, skill) FROM stdin;
\.


--
-- Data for Name: announcements; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.announcements (id, active, author_email, author_name, category, content, created_at, image_url, is_urgent, title, updated_at, view_count) FROM stdin;
1328	t	admin@ijaa.com	Admin User	GENERAL	We are excited to welcome you back to our platform. Stay tuned for new features and updates.	2025-08-10 15:14:30.624232	\N	f	Welcome Back!	2025-08-10 15:14:30.624232	0
1329	t	events@ijaa.com	Event Manager	EVENT	Join us for an evening of networking and fun at the Alumni Meetup. Date: April 20, 2025. Location: Coffee House, Gulshan.	2025-08-10 15:14:30.629504	\N	f	Upcoming Event: Alumni Meetup	2025-08-10 15:14:30.629504	0
1330	t	system@ijaa.com	System Admin	NEWS	We are excited to announce the launch of our new user interface. Please check it out and provide feedback.	2025-08-10 15:14:30.63126	https://example.com/ui-update.jpg	t	Important Update: New User Interface	2025-08-10 15:14:30.63126	0
1331	t	system@ijaa.com	System Admin	URGENT	Scheduled maintenance will occur on Sunday from 2-4 AM. The platform will be temporarily unavailable.	2025-08-10 15:14:30.632972	\N	t	Urgent: System Maintenance	2025-08-10 15:14:30.632972	0
1332	t	career@ijaa.com	Career Manager	EVENT	Registration for the annual career fair is now open. Limited spots available!	2025-08-10 15:14:30.634394	https://example.com/career-fair.jpg	f	Career Fair Registration Open	2025-08-10 15:14:30.634394	0
1333	t	product@ijaa.com	Product Team	NEWS	We've launched a new alumni directory feature. Connect with fellow alumni easily!	2025-08-10 15:14:30.635978	\N	f	New Feature: Alumni Directory	2025-08-10 15:14:30.635978	0
1334	t	community@ijaa.com	Community Manager	SUCCESS	Congratulations to John Doe (Class of 2018) for being promoted to Senior Software Engineer at Google!	2025-08-10 15:14:30.637182	\N	f	Alumni Success Story: John Doe	2025-08-10 15:14:30.637182	0
1335	t	support@ijaa.com	Support Team	GENERAL	The platform will have limited support during the upcoming holidays. Regular support will resume on January 2nd.	2025-08-10 15:14:30.638411	\N	f	Holiday Schedule	2025-08-10 15:14:30.638411	0
1336	t	programs@ijaa.com	Program Manager	PROGRAM	We're launching a new mentorship program. Senior alumni can mentor junior alumni. Sign up now!	2025-08-10 15:14:30.642633	https://example.com/mentorship.jpg	t	Mentorship Program Launch	2025-08-10 15:14:30.642633	0
1337	t	research@ijaa.com	Research Team	SURVEY	Please take a moment to complete our annual alumni survey. Your feedback helps us improve our services.	2025-08-10 15:14:30.648026	\N	f	Alumni Survey	2025-08-10 15:14:30.648026	0
\.


--
-- Data for Name: calendar_integrations; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.calendar_integrations (id, access_token, calendar_id, calendar_name, calendar_type, created_at, is_active, last_sync_error, last_sync_time, refresh_token, sync_events, sync_invitations, sync_settings, token_expiry, updated_at, username, calendar_url, sync_frequency_hours, sync_from_external, sync_recurring_events, sync_reminders, sync_to_external) FROM stdin;
\.


--
-- Data for Name: connections; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.connections (id, created_at, receiver_username, requester_username, status) FROM stdin;
1	\N	rakib.hassan	current_user	ACCEPTED
2	\N	sarah.ahmed	current_user	PENDING
3	\N	current_user	fatima.khan	ACCEPTED
\.


--
-- Data for Name: event_analytics; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.event_analytics (id, actual_attendees, attendance_rate, confirmed_attendees, created_at, declined_attendees, event_id, last_updated, maybe_attendees, no_shows, notes, pending_responses, response_rate, total_invitations, updated_at, average_response_time_hours, event_end_date, event_start_date, event_title, first_rsvp_time, is_completed, last_rsvp_time, organizer_username, total_comments, total_media_uploads, total_reminders, engagement_rate) FROM stdin;
165	25	85	25	2025-08-10 15:14:30.568307	3	1	2025-08-10 15:14:30.565494	5	0	\N	17	85	50	2025-08-10 15:14:30.568307	0	2025-01-01 23:00:00	2025-01-01 18:00:00	New Year Celebration 2025	2024-12-15 10:00:00	t	2024-12-30 18:00:00	john.doe	15	8	3	75
166	150	92	150	2025-08-10 15:14:30.575426	10	2	2025-08-10 15:14:30.565524	20	0	\N	20	92	200	2025-08-10 15:14:30.575426	0	2025-03-15 17:00:00	2025-03-15 09:00:00	Tech Conference 2025	2024-12-01 09:00:00	t	2025-03-10 17:00:00	jane.smith	25	12	5	88
167	60	78	60	2025-08-10 15:14:30.578472	5	3	2025-08-10 15:14:30.565534	10	0	\N	5	78	80	2025-08-10 15:14:30.578472	0	2025-02-10 16:00:00	2025-02-10 14:00:00	Online Workshop: AI Basics	2024-12-20 14:00:00	t	2025-02-08 16:00:00	mike.johnson	12	6	2	82
168	25	83	25	2025-08-10 15:14:30.581185	2	4	2025-08-10 15:14:30.565541	3	0	\N	0	83	30	2025-08-10 15:14:30.581185	0	2025-04-20 21:00:00	2025-04-20 18:00:00	Alumni Meetup - Dhaka	2025-03-01 18:00:00	t	2025-04-18 21:00:00	sarah.wilson	8	4	1	80
169	120	80	120	2025-08-10 15:14:30.584156	8	5	2025-08-10 15:14:30.565549	15	0	\N	7	80	150	2025-08-10 15:14:30.584156	0	2025-05-10 16:00:00	2025-05-10 10:00:00	Career Fair 2025	2025-01-01 10:00:00	t	2025-05-08 16:00:00	david.brown	18	10	3	85
170	80	80	80	2025-08-10 15:14:30.586603	5	6	2025-08-10 15:14:30.565555	10	0	\N	5	80	100	2025-08-10 15:14:30.586603	0	2025-06-15 23:00:00	2025-06-15 19:00:00	Alumni Reunion 2025	2025-02-01 19:00:00	f	2025-06-12 23:00:00	john.doe	15	8	2	83
171	20	80	20	2025-08-10 15:14:30.588478	2	7	2025-08-10 15:14:30.565562	3	0	\N	0	80	25	2025-08-10 15:14:30.588478	0	2025-07-05 17:00:00	2025-07-01 09:00:00	Web Development Bootcamp	2025-03-01 09:00:00	f	2025-06-28 17:00:00	jane.smith	6	4	1	85
172	45	75	45	2025-08-10 15:14:30.590453	4	8	2025-08-10 15:14:30.565569	8	0	\N	3	75	60	2025-08-10 15:14:30.590453	0	2025-08-15 22:00:00	2025-08-15 19:00:00	Startup Pitch Night	2025-04-01 19:00:00	f	2025-08-12 22:00:00	mike.johnson	10	6	2	78
173	28	80	28	2025-08-10 15:14:30.592432	2	9	2025-08-10 15:14:30.565576	4	0	\N	1	80	35	2025-08-10 15:14:30.592432	0	2025-09-20 16:00:00	2025-09-20 10:00:00	Data Science Workshop	2025-05-01 10:00:00	f	2025-09-17 16:00:00	sarah.wilson	7	4	1	82
174	65	81	65	2025-08-10 15:14:30.595613	3	10	2025-08-10 15:14:30.565582	10	0	\N	2	81	80	2025-08-10 15:14:30.595613	0	2025-10-05 18:00:00	2025-10-05 08:00:00	Alumni Sports Day	2025-06-01 08:00:00	f	2025-10-02 18:00:00	david.brown	12	8	2	84
\.


--
-- Data for Name: event_comments; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.event_comments (id, content, created_at, event_id, is_deleted, is_edited, likes, parent_comment_id, replies, updated_at, username) FROM stdin;
851	This is going to be an amazing celebration! 🎉	2025-08-10 15:14:30.312025	1	f	f	0	\N	0	2025-08-10 15:14:30.312025	john.doe
852	Can't wait to see the fireworks display!	2025-08-10 15:14:30.318195	1	f	f	0	\N	0	2025-08-10 15:14:30.318195	jane.smith
853	Will there be live music?	2025-08-10 15:14:30.319667	1	f	f	0	\N	0	2025-08-10 15:14:30.319667	mike.johnson
854	The venue looks perfect for this event	2025-08-10 15:14:30.320746	1	f	f	0	\N	0	2025-08-10 15:14:30.320746	sarah.wilson
855	Looking forward to meeting everyone!	2025-08-10 15:14:30.321667	1	f	f	0	\N	0	2025-08-10 15:14:30.321667	david.brown
856	Great lineup of speakers this year!	2025-08-10 15:14:30.322595	2	f	f	0	\N	0	2025-08-10 15:14:30.322595	john.doe
857	The networking sessions are always valuable	2025-08-10 15:14:30.323426	2	f	f	0	\N	0	2025-08-10 15:14:30.323426	jane.smith
858	Will there be workshops on the latest tech trends?	2025-08-10 15:14:30.324276	2	f	f	0	\N	0	2025-08-10 15:14:30.324276	mike.johnson
859	Perfect opportunity to learn from industry experts	2025-08-10 15:14:30.325217	2	f	f	0	\N	0	2025-08-10 15:14:30.325217	sarah.wilson
860	The venue is easily accessible	2025-08-10 15:14:30.326225	2	f	f	0	\N	0	2025-08-10 15:14:30.326225	david.brown
861	AI is transforming every industry!	2025-08-10 15:14:30.327285	3	f	f	0	\N	0	2025-08-10 15:14:30.327285	john.doe
862	This workshop will be perfect for beginners	2025-08-10 15:14:30.330011	3	f	f	0	\N	0	2025-08-10 15:14:30.330011	jane.smith
863	Online format makes it accessible to everyone	2025-08-10 15:14:30.332008	3	f	f	0	\N	0	2025-08-10 15:14:30.332008	mike.johnson
864	Looking forward to the hands-on exercises	2025-08-10 15:14:30.334182	3	f	f	0	\N	0	2025-08-10 15:14:30.334182	sarah.wilson
865	Will there be certificates provided?	2025-08-10 15:14:30.335833	3	f	f	0	\N	0	2025-08-10 15:14:30.335833	david.brown
866	Coffee and networking - perfect combination!	2025-08-10 15:14:30.33697	4	f	f	0	\N	0	2025-08-10 15:14:30.33697	john.doe
867	Great venue choice for casual networking	2025-08-10 15:14:30.337927	4	f	f	0	\N	0	2025-08-10 15:14:30.337927	jane.smith
868	Will there be any structured networking activities?	2025-08-10 15:14:30.338814	4	f	f	0	\N	0	2025-08-10 15:14:30.338814	mike.johnson
869	Looking forward to meeting fellow alumni	2025-08-10 15:14:30.339649	4	f	f	0	\N	0	2025-08-10 15:14:30.339649	sarah.wilson
870	Perfect timing for a weekend meetup	2025-08-10 15:14:30.340391	4	f	f	0	\N	0	2025-08-10 15:14:30.340391	david.brown
871	Great opportunity to explore new career paths	2025-08-10 15:14:30.341109	5	f	f	0	\N	0	2025-08-10 15:14:30.341109	john.doe
872	Will there be companies from the tech sector?	2025-08-10 15:14:30.342052	5	f	f	0	\N	0	2025-08-10 15:14:30.342052	jane.smith
873	Perfect timing for job seekers	2025-08-10 15:14:30.342883	5	f	f	0	\N	0	2025-08-10 15:14:30.342883	mike.johnson
874	Looking forward to the company presentations	2025-08-10 15:14:30.343626	5	f	f	0	\N	0	2025-08-10 15:14:30.343626	sarah.wilson
875	Will there be resume review sessions?	2025-08-10 15:14:30.345181	5	f	f	0	\N	0	2025-08-10 15:14:30.345181	david.brown
\.


--
-- Data for Name: event_invitations; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.event_invitations (id, created_at, event_id, invited_by_username, invited_username, is_read, is_responded, personal_message, updated_at) FROM stdin;
513	2025-08-10 15:14:30.420287	1	john.doe	alex.chen	f	f	You're invited to our New Year celebration!	2025-08-10 15:14:30.420287
514	2025-08-10 15:14:30.425114	1	jane.smith	emma.wilson	f	f	Join us for an amazing New Year party!	2025-08-10 15:14:30.425114
515	2025-08-10 15:14:30.428743	1	mike.johnson	robert.kim	f	f	Don't miss the New Year celebration!	2025-08-10 15:14:30.428743
516	2025-08-10 15:14:30.431514	2	john.doe	alex.chen	f	f	You're invited to our tech conference!	2025-08-10 15:14:30.431514
517	2025-08-10 15:14:30.434301	2	jane.smith	emma.wilson	f	f	Great networking opportunity at the tech conference	2025-08-10 15:14:30.434301
518	2025-08-10 15:14:30.436849	2	mike.johnson	robert.kim	f	f	Join us for the annual tech conference	2025-08-10 15:14:30.436849
519	2025-08-10 15:14:30.439517	3	john.doe	alex.chen	f	f	Learn AI basics in our online workshop!	2025-08-10 15:14:30.439517
520	2025-08-10 15:14:30.442512	3	jane.smith	emma.wilson	f	f	Perfect workshop for data science enthusiasts	2025-08-10 15:14:30.442512
521	2025-08-10 15:14:30.445262	3	mike.johnson	robert.kim	f	f	Join our AI workshop to learn new skills	2025-08-10 15:14:30.445262
522	2025-08-10 15:14:30.447698	4	john.doe	alex.chen	f	f	Join us for coffee and networking!	2025-08-10 15:14:30.447698
523	2025-08-10 15:14:30.450125	4	jane.smith	emma.wilson	f	f	Casual meetup with fellow alumni	2025-08-10 15:14:30.450125
524	2025-08-10 15:14:30.452167	4	mike.johnson	robert.kim	f	f	Great opportunity to network over coffee	2025-08-10 15:14:30.452167
525	2025-08-10 15:14:30.45384	5	john.doe	alex.chen	f	f	Explore job opportunities at our career fair!	2025-08-10 15:14:30.45384
526	2025-08-10 15:14:30.455465	5	jane.smith	emma.wilson	f	f	Great companies will be at the career fair	2025-08-10 15:14:30.455465
527	2025-08-10 15:14:30.457212	5	mike.johnson	robert.kim	f	f	Don't miss the career opportunities!	2025-08-10 15:14:30.457212
\.


--
-- Data for Name: event_media; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.event_media (id, caption, created_at, event_id, file_name, file_size, file_type, file_url, is_approved, likes, media_type, updated_at, uploaded_by_username) FROM stdin;
307	New Year Celebration Banner	2025-08-10 15:14:30.370437	1	new_year_banner.jpg	2048576	image/jpeg	https://example.com/media/new_year_banner.jpg	t	0	IMAGE	2025-08-10 15:14:30.370437	john.doe
308	Venue Preview	2025-08-10 15:14:30.374304	1	venue_photo.jpg	1536000	image/jpeg	https://example.com/media/venue_photo.jpg	t	0	IMAGE	2025-08-10 15:14:30.374304	jane.smith
309	Conference Logo	2025-08-10 15:14:30.375803	2	tech_conference_logo.png	512000	image/png	https://example.com/media/tech_conference_logo.png	t	0	IMAGE	2025-08-10 15:14:30.375803	mike.johnson
310	Speaker Lineup	2025-08-10 15:14:30.377797	2	speaker_lineup.pdf	1024000	application/pdf	https://example.com/media/speaker_lineup.pdf	t	0	DOCUMENT	2025-08-10 15:14:30.377797	sarah.wilson
311	Workshop Poster	2025-08-10 15:14:30.380426	3	ai_workshop_poster.jpg	3072000	image/jpeg	https://example.com/media/ai_workshop_poster.jpg	t	0	IMAGE	2025-08-10 15:14:30.380426	david.brown
312	Workshop Agenda	2025-08-10 15:14:30.382655	3	workshop_agenda.pdf	512000	application/pdf	https://example.com/media/workshop_agenda.pdf	t	0	DOCUMENT	2025-08-10 15:14:30.382655	john.doe
313	Venue Photo	2025-08-10 15:14:30.384346	4	coffee_house_photo.jpg	2048000	image/jpeg	https://example.com/media/coffee_house_photo.jpg	t	0	IMAGE	2025-08-10 15:14:30.384346	jane.smith
314	Career Fair Banner	2025-08-10 15:14:30.386188	5	career_fair_banner.jpg	4096000	image/jpeg	https://example.com/media/career_fair_banner.jpg	t	0	IMAGE	2025-08-10 15:14:30.386188	mike.johnson
315	Participating Companies	2025-08-10 15:14:30.388143	5	participating_companies.pdf	1536000	application/pdf	https://example.com/media/participating_companies.pdf	t	0	DOCUMENT	2025-08-10 15:14:30.388143	sarah.wilson
\.


--
-- Data for Name: event_participations; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.event_participations (id, created_at, event_id, message, participant_username, status, updated_at) FROM stdin;
855	2025-08-10 15:14:30.215942	1	Looking forward to the celebration! 🎉	john.doe	GOING	2025-08-10 15:14:30.215942
856	2025-08-10 15:14:30.22198	1	Can't wait to see everyone!	jane.smith	GOING	2025-08-10 15:14:30.22198
857	2025-08-10 15:14:30.22456	1	I'll try to make it	mike.johnson	MAYBE	2025-08-10 15:14:30.22456
858	2025-08-10 15:14:30.226839	1	Excited for the new year!	sarah.wilson	GOING	2025-08-10 15:14:30.226839
859	2025-08-10 15:14:30.230366	1	Sorry, I have other plans	david.brown	NOT_GOING	2025-08-10 15:14:30.230366
860	2025-08-10 15:14:30.233295	2	Great opportunity for networking	john.doe	GOING	2025-08-10 15:14:30.233295
861	2025-08-10 15:14:30.236101	2	Looking forward to the tech talks	jane.smith	GOING	2025-08-10 15:14:30.236101
862	2025-08-10 15:14:30.238423	2	Will be there for sure	mike.johnson	GOING	2025-08-10 15:14:30.238423
863	2025-08-10 15:14:30.241475	2	Depends on my schedule	sarah.wilson	MAYBE	2025-08-10 15:14:30.241475
864	2025-08-10 15:14:30.243222	2	Tech conferences are always valuable	david.brown	GOING	2025-08-10 15:14:30.243222
865	2025-08-10 15:14:30.246522	3	AI is the future!	john.doe	GOING	2025-08-10 15:14:30.246522
866	2025-08-10 15:14:30.249267	3	Perfect for my data science career	jane.smith	GOING	2025-08-10 15:14:30.249267
867	2025-08-10 15:14:30.251446	3	Online workshops are convenient	mike.johnson	GOING	2025-08-10 15:14:30.251446
868	2025-08-10 15:14:30.253584	3	I'll join if I'm free	sarah.wilson	MAYBE	2025-08-10 15:14:30.253584
869	2025-08-10 15:14:30.255317	3	Not my area of interest	david.brown	NOT_GOING	2025-08-10 15:14:30.255317
870	2025-08-10 15:14:30.256863	4	Love meeting fellow alumni	john.doe	GOING	2025-08-10 15:14:30.256863
871	2025-08-10 15:14:30.258305	4	Coffee and networking sounds perfect	jane.smith	GOING	2025-08-10 15:14:30.258305
872	2025-08-10 15:14:30.259999	4	I'll try to join	mike.johnson	MAYBE	2025-08-10 15:14:30.259999
873	2025-08-10 15:14:30.262572	4	Looking forward to it!	sarah.wilson	GOING	2025-08-10 15:14:30.262572
874	2025-08-10 15:14:30.264646	4	Always good to network	david.brown	GOING	2025-08-10 15:14:30.264646
875	2025-08-10 15:14:30.26686	5	Great opportunity to explore new career paths	john.doe	GOING	2025-08-10 15:14:30.26686
876	2025-08-10 15:14:30.268794	5	Will there be companies from the tech sector?	jane.smith	GOING	2025-08-10 15:14:30.268794
877	2025-08-10 15:14:30.270774	5	Perfect timing for job seekers	mike.johnson	GOING	2025-08-10 15:14:30.270774
878	2025-08-10 15:14:30.272982	5	Looking forward to the company presentations	sarah.wilson	GOING	2025-08-10 15:14:30.272982
879	2025-08-10 15:14:30.274711	5	Will there be resume review sessions?	david.brown	GOING	2025-08-10 15:14:30.274711
\.


--
-- Data for Name: event_reminders; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.event_reminders (id, channel, created_at, custom_message, event_id, is_active, is_sent, reminder_time, reminder_type, updated_at, username) FROM stdin;
\.


--
-- Data for Name: event_templates; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.event_templates (id, created_at, created_by_username, default_duration_minutes, default_end_time, default_start_time, description, event_type, invite_message, is_online, is_public, is_recurring, location, max_participants, meeting_link, notes, organizer_email, organizer_name, privacy, recurrence_days, recurrence_interval, recurrence_type, tags, template_name, title, updated_at, usage_count, category, default_recurrence_days, default_recurrence_interval, default_recurrence_type, is_active, name, supports_recurrence, total_ratings, average_rating) FROM stdin;
210	2025-08-10 15:14:30.481045	john.doe	480	17:00:00	09:00:00	Annual technology conference with industry experts	CONFERENCE	Join us for the latest in technology!	f	t	f	Conference Center	500	\N	\N	tech@ijaa.com	Tech Lead	PUBLIC	\N	\N	\N	tech,conference,networking	Tech Conference Template	Annual Tech Conference	2025-08-10 15:14:30.481045	0	CONFERENCE	\N	1	\N	t	Tech Conference Template	f	0	0
211	2025-08-10 15:14:30.488091	jane.smith	180	13:00:00	10:00:00	Hands-on workshop for skill development	WORKSHOP	Learn new skills in this interactive workshop!	f	t	f	Training Room	50	\N	\N	workshop@ijaa.com	Workshop Lead	PUBLIC	\N	\N	\N	workshop,learning,skills	Workshop Template	Interactive Workshop	2025-08-10 15:14:30.488091	0	WORKSHOP	\N	1	\N	t	Workshop Template	f	0	0
212	2025-08-10 15:14:30.490059	mike.johnson	120	20:00:00	18:00:00	Casual networking meetup for alumni	MEETUP	Connect with fellow alumni!	f	t	f	Coffee Shop	30	\N	\N	community@ijaa.com	Community Manager	PUBLIC	\N	\N	\N	networking,alumni,coffee	Networking Meetup	Alumni Networking	2025-08-10 15:14:30.490059	0	NETWORKING	\N	1	\N	t	Networking Meetup	f	0	0
213	2025-08-10 15:14:30.49175	sarah.wilson	360	16:00:00	10:00:00	Job fair with multiple companies	CAREER_FAIR	Explore job opportunities!	f	t	f	University Hall	200	\N	\N	career@ijaa.com	Career Services	PUBLIC	\N	\N	\N	career,jobs,fair	Career Fair Template	Career Fair	2025-08-10 15:14:30.49175	0	CAREER	\N	1	\N	t	Career Fair Template	f	0	0
214	2025-08-10 15:14:30.493749	david.brown	60	15:00:00	14:00:00	Virtual webinar with remote participation	WEBINAR	Join our online webinar!	t	t	f	Virtual	100	https://meet.google.com/	\N	webinar@ijaa.com	Webinar Host	PUBLIC	\N	\N	\N	webinar,online,virtual	Online Webinar	Online Webinar	2025-08-10 15:14:30.493749	0	WEBINAR	\N	1	\N	t	Online Webinar	f	0	0
215	2025-08-10 15:14:30.496508	john.doe	120	18:00:00	16:00:00	Recurring study group for students	STUDY_GROUP	Join our weekly study sessions!	f	f	f	Library	20	\N	\N	study@ijaa.com	Study Coordinator	PRIVATE	\N	\N	\N	study,academic,weekly	Weekly Study Group	Weekly Study Group	2025-08-10 15:14:30.496508	0	ACADEMIC	MONDAY,WEDNESDAY,FRIDAY	1	WEEKLY	t	Weekly Study Group	t	0	0
216	2025-08-10 15:14:30.498561	jane.smith	180	22:00:00	19:00:00	Monthly dinner for alumni networking	DINNER	Join us for dinner and networking!	f	f	f	Restaurant	40	\N	\N	dinner@ijaa.com	Dinner Coordinator	PRIVATE	\N	\N	\N	dinner,alumni,monthly	Monthly Alumni Dinner	Monthly Alumni Dinner	2025-08-10 15:14:30.498561	0	SOCIAL	\N	1	MONTHLY	t	Monthly Alumni Dinner	t	0	0
217	2025-08-10 15:14:30.500195	mike.johnson	240	22:00:00	18:00:00	Annual reunion with dinner and entertainment	REUNION	Annual alumni reunion celebration!	f	t	f	Hotel Ballroom	150	\N	\N	reunion@ijaa.com	Reunion Coordinator	PUBLIC	\N	\N	\N	reunion,annual,celebration	Annual Reunion	Annual Alumni Reunion	2025-08-10 15:14:30.500195	0	REUNION	\N	1	\N	t	Annual Reunion	f	0	0
218	2025-08-10 15:14:30.501366	sarah.wilson	600	18:00:00	08:00:00	Annual sports day with various activities	SPORTS	Join us for a day of sports and fun!	f	t	f	Sports Complex	100	\N	\N	sports@ijaa.com	Sports Coordinator	PUBLIC	\N	\N	\N	sports,activities,fun	Sports Day	Alumni Sports Day	2025-08-10 15:14:30.501366	0	SPORTS	\N	1	\N	t	Sports Day	f	0	0
219	2025-08-10 15:14:30.502647	david.brown	60	16:00:00	15:00:00	One-on-one mentorship sessions	MENTORSHIP	Connect with mentors for career guidance!	f	f	f	Meeting Room	10	\N	\N	mentorship@ijaa.com	Mentorship Coordinator	PRIVATE	\N	\N	\N	mentorship,career,guidance	Mentorship Program	Mentorship Session	2025-08-10 15:14:30.502647	0	MENTORSHIP	\N	1	\N	t	Mentorship Program	f	0	0
\.


--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.events (id, active, created_at, current_participants, description, end_date, event_type, is_online, location, max_participants, meeting_link, organizer, start_date, title, updated_at, organizer_email, organizer_name, created_by_username, invite_message, privacy) FROM stdin;
1172	t	2025-08-10 15:14:30.138397	0	Celebrate the new year with fireworks, music, and networking opportunities	2025-01-01 23:00:00	CELEBRATION	f	Dhaka Club	200	\N	\N	2025-01-01 18:00:00	New Year Celebration 2025	2025-08-10 15:14:30.138397	admin@ijaa.com	Admin User	john.doe	You're invited to join us at this exciting event!	PUBLIC
1173	t	2025-08-10 15:14:30.147776	0	Annual technology conference with industry experts and networking sessions	2025-03-15 17:00:00	CONFERENCE	f	Bangabandhu International Conference Center	500	\N	\N	2025-03-15 09:00:00	Tech Conference 2025	2025-08-10 15:14:30.147776	events@ijaa.com	Event Manager	jane.smith	You're invited to join us at this exciting event!	PUBLIC
1174	t	2025-08-10 15:14:30.150965	0	Learn the fundamentals of artificial intelligence and machine learning	2025-02-10 16:00:00	WORKSHOP	t	Virtual	100	https://meet.google.com/abc-defg-hij	\N	2025-02-10 14:00:00	Online Workshop: AI Basics	2025-08-10 15:14:30.150965	tech@ijaa.com	Tech Lead	mike.johnson	You're invited to join us at this exciting event!	PUBLIC
1175	t	2025-08-10 15:14:30.153876	0	Connect with fellow alumni over coffee and networking in Dhaka	2025-04-20 21:00:00	MEETUP	f	Coffee House, Gulshan	50	\N	\N	2025-04-20 18:00:00	Alumni Meetup - Dhaka	2025-08-10 15:14:30.153876	community@ijaa.com	Community Manager	sarah.wilson	You're invited to join us at this exciting event!	PUBLIC
1176	t	2025-08-10 15:14:30.157163	0	Explore job opportunities with leading companies and startups	2025-05-10 16:00:00	CAREER_FAIR	f	University Campus	300	\N	\N	2025-05-10 10:00:00	Career Fair 2025	2025-08-10 15:14:30.157163	career@ijaa.com	Career Services	david.brown	You're invited to join us at this exciting event!	PUBLIC
1177	t	2025-08-10 15:14:30.161086	0	Annual alumni reunion with dinner and entertainment	2025-06-15 23:00:00	REUNION	f	Radisson Blu Hotel	150	\N	\N	2025-06-15 19:00:00	Alumni Reunion 2025	2025-08-10 15:14:30.161086	reunion@ijaa.com	Reunion Coordinator	john.doe	You're invited to join us at this exciting event!	PUBLIC
1178	t	2025-08-10 15:14:30.165203	0	Intensive web development bootcamp for beginners	2025-07-05 17:00:00	BOOTCAMP	f	Tech Hub Dhaka	30	\N	\N	2025-07-01 09:00:00	Web Development Bootcamp	2025-08-10 15:14:30.165203	education@ijaa.com	Education Team	jane.smith	You're invited to join us at this exciting event!	PUBLIC
1179	t	2025-08-10 15:14:30.168787	0	Watch innovative startups pitch their ideas to investors	2025-08-15 22:00:00	PITCH_NIGHT	f	Innovation Hub	80	\N	\N	2025-08-15 19:00:00	Startup Pitch Night	2025-08-10 15:14:30.168787	startup@ijaa.com	Startup Coordinator	mike.johnson	You're invited to join us at this exciting event!	PUBLIC
1180	t	2025-08-10 15:14:30.171219	0	Hands-on workshop on data science and machine learning	2025-09-20 16:00:00	WORKSHOP	f	Tech Institute	40	\N	\N	2025-09-20 10:00:00	Data Science Workshop	2025-08-10 15:14:30.171219	data@ijaa.com	Data Science Lead	sarah.wilson	You're invited to join us at this exciting event!	PUBLIC
1181	t	2025-08-10 15:14:30.173406	0	Annual sports day with various activities and competitions	2025-10-05 18:00:00	SPORTS	f	University Sports Complex	120	\N	\N	2025-10-05 08:00:00	Alumni Sports Day	2025-08-10 15:14:30.173406	sports@ijaa.com	Sports Coordinator	david.brown	You're invited to join us at this exciting event!	PUBLIC
\.


--
-- Data for Name: experiences; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.experiences (id, company, description, period, title, created_at, updated_at, username, user_id) FROM stdin;
6	Tech Solutions Ltd	szxx zxc sdcvsdvsd	xcvxcv xcv cx	Software Engineer	2025-07-29 00:29:54.541851	2025-07-29 00:29:54.541899	mdsahal.info@gmail.com	ce6ceb99-edd2-4448-b85c-a85ad187540e
7	Tech Solutions Ltd	zcxvxxxxxxxxxxxxxxxxxxxxxx	sdc dddd dzc	dczxczd	2025-08-02 11:53:13.341344	2025-08-02 11:53:13.341384	afrineva28@gmail.com	ce6ceb99-edd2-4448-b85c-a85ad187540d
\.


--
-- Data for Name: feature_flags; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.feature_flags (id, created_at, description, enabled, feature_name, updated_at) FROM stdin;
1876	2025-08-10 15:14:30.065532	Enable new user interface with modern design	t	NEW_UI	2025-08-10 15:14:30.065567
1877	2025-08-10 15:14:30.087304	Enable real-time chat functionality between alumni	f	CHAT_FEATURE	2025-08-10 15:14:30.08731
1878	2025-08-10 15:14:30.089889	Enable event registration system for alumni events	t	EVENT_REGISTRATION	2025-08-10 15:14:30.089895
1879	2025-08-10 15:14:30.091783	Enable payment processing for event registrations	f	PAYMENT_INTEGRATION	2025-08-10 15:14:30.091787
1880	2025-08-10 15:14:30.093336	Enable social media login options (Google, Facebook)	t	SOCIAL_LOGIN	2025-08-10 15:14:30.093343
1881	2025-08-10 15:14:30.096533	Enable dark mode theme for better user experience	t	DARK_MODE	2025-08-10 15:14:30.096538
1882	2025-08-10 15:14:30.098943	Enable push notifications for important updates	t	NOTIFICATIONS	2025-08-10 15:14:30.098948
1883	2025-08-10 15:14:30.101012	Enable advanced search with filters and sorting	f	ADVANCED_SEARCH	2025-08-10 15:14:30.101018
1884	2025-08-10 15:14:30.10316	Enable public alumni directory feature	t	ALUMNI_DIRECTORY	2025-08-10 15:14:30.103173
1885	2025-08-10 15:14:30.10518	Enable mentorship program matching	f	MENTORSHIP_PROGRAM	2025-08-10 15:14:30.10519
\.


--
-- Data for Name: interests; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.interests (id, created_at, interest, updated_at, user_id, username) FROM stdin;
1	2025-07-29 00:30:04.73926	bnvjh	2025-07-29 00:30:04.739421	ce6ceb99-edd2-4448-b85c-a85ad187540e	mdsahal.info@gmail.com
2	2025-07-29 00:30:09.834097	kjnljoi	2025-07-29 00:30:09.83413	ce6ceb99-edd2-4448-b85c-a85ad187540e	mdsahal.info@gmail.com
3	2025-08-02 02:23:14.281905	,jbnkjj	2025-08-02 02:23:14.281992	ce6ceb99-edd2-4448-b85c-a85ad187540d	afrineva28@gmail.com
4	2025-08-02 23:23:50.436443	cvbcvbcv	2025-08-02 23:23:50.436467	ce6ceb99-edd2-4448-b85c-a85ad187540e	mdsahal.info@gmail.com
\.


--
-- Data for Name: profiles; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.profiles (id, batch, bio, created_at, facebook, github, instagram, linkedin, location, name, phone, profession, skills, twitter, updated_at, website, linked_in, show_linked_in, show_phone, show_website, username, department, email, show_email, connections, show_facebook, user_id) FROM stdin;
3	2018	Designing intuitive user experiences.	2025-07-27 23:40:20.539007	https://facebook.com/ayesha.r	\N	\N	\N	Chittagong, Bangladesh	Ayesha Rahman	+8801711000001	UI/UX Designer	\N	\N	2025-07-27 23:40:20.551153	https://ayesha.design	https://linkedin.com/in/ayeshar	t	f	t	ayesha@gmail.com	\N	ayesha@example.com	t	0	f	ce6ceb99-edd2-4448-b85c-a85ad187540c
2	9	I am a teacher.	2025-07-27 20:53:57.35387	https://linkedin.com/in/johnsmith	\N	\N	\N	Dhaka	Saima Rahman	01813279398	Lecturer	\N	\N	2025-07-30 13:43:40.429239	https://johnsmith.dev	https://linkedin.com/in/johnsmith	t	t	t	afrineva28@gmail.com	\N	me.sahal2000@gmail.com	t	0	t	ce6ceb99-edd2-4448-b85c-a85ad187540d
4	string	string	2025-08-02 16:06:16.630105	string	\N	\N	\N	string	string	string	string	\N	\N	2025-08-02 16:06:16.659099	string	string	t	t	t	admin@ijaa.com	\N	string	t	0	t	8bd54f0a-a5f8-4ef5-a6ad-c14406c0bcaf
1	9	Software engineer and content creator Software engineer and content creator Software engineer and content creator Software engineer and content creator Software engineer and content creator	\N	https://facebook.com/mdsahal	\N	\N	\N	Bangladesh	Md Sahal	+8801700000012	Software Engineer	\N	\N	2025-08-02 23:23:24.487315	https://sahal.dev	https://linkedin.com/in/mdsahal	t	f	t	mdsahal.info@gmail.com	Ophthalmology	sahal@example.com	t	\N	f	ce6ceb99-edd2-4448-b85c-a85ad187540e
\.


--
-- Data for Name: recurring_events; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.recurring_events (id, active, created_at, created_by_username, current_participants, description, end_date, event_type, invite_message, is_online, is_series, is_template, location, max_participants, meeting_link, organizer_email, organizer_name, parent_event_id, privacy, recurrence_days, recurrence_end_date, recurrence_interval, recurrence_type, start_date, title, updated_at, generate_instances, max_occurrences) FROM stdin;
101	t	2025-08-10 15:14:30.525507	john.doe	0	Weekly study sessions for students	2025-01-06 18:00:00	STUDY_GROUP	Join our recurring event!	f	f	f	Library	20	\N	study@ijaa.com	Study Coordinator	\N	PUBLIC	MONDAY,WEDNESDAY,FRIDAY	2025-12-31 18:00:00	1	WEEKLY	2025-01-06 16:00:00	Weekly Study Group	2025-08-10 15:14:30.525507	t	52
102	t	2025-08-10 15:14:30.53341	jane.smith	0	Monthly dinner for alumni networking	2025-01-15 22:00:00	DINNER	Join our recurring event!	f	f	f	Restaurant	40	\N	dinner@ijaa.com	Dinner Coordinator	\N	PUBLIC	\N	2025-12-31 22:00:00	1	MONTHLY	2025-01-15 19:00:00	Monthly Alumni Dinner	2025-08-10 15:14:30.53341	t	12
103	t	2025-08-10 15:14:30.535829	mike.johnson	0	Bi-weekly technology discussions	2025-01-08 20:00:00	MEETUP	Join our recurring event!	f	f	f	Tech Hub	30	\N	tech@ijaa.com	Tech Lead	\N	PUBLIC	WEDNESDAY	2025-12-31 20:00:00	2	WEEKLY	2025-01-08 18:00:00	Bi-weekly Tech Meetup	2025-08-10 15:14:30.535829	t	26
104	t	2025-08-10 15:14:30.537935	sarah.wilson	0	Quarterly board meetings for alumni association	2025-01-20 16:00:00	MEETING	Join our recurring event!	f	f	f	Conference Room	15	\N	board@ijaa.com	Board Secretary	\N	PUBLIC	\N	2025-12-31 16:00:00	3	MONTHLY	2025-01-20 14:00:00	Quarterly Board Meeting	2025-08-10 15:14:30.537935	t	4
105	t	2025-08-10 15:14:30.539394	david.brown	0	Daily morning exercise sessions	2025-01-01 07:00:00	EXERCISE	Join our recurring event!	f	f	f	Sports Complex	50	\N	fitness@ijaa.com	Fitness Instructor	\N	PUBLIC	MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY	2025-12-31 07:00:00	1	DAILY	2025-01-01 06:00:00	Daily Morning Exercise	2025-08-10 15:14:30.539394	t	260
\.


--
-- Data for Name: reports; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.reports (id, admin_notes, assigned_to, attachment_url, category, created_at, description, priority, reporter_email, reporter_name, status, title, updated_at) FROM stdin;
1582	\N	\N	\N	USER_REPORT	2025-08-10 15:14:30.669497	User jane.smith posted offensive content on the platform.	MEDIUM	john.doe@email.com	John Doe	PENDING	User Behavior Report	2025-08-10 15:14:30.669497
1583	Investigating spam content	Admin User	\N	CONTENT_REPORT	2025-08-10 15:14:30.673944	User sarah.wilson posted spam on the platform.	HIGH	mike.johnson@email.com	Mike Johnson	IN_PROGRESS	Content Moderation	2025-08-10 15:14:30.673944
1584	\N	\N	\N	BUG_REPORT	2025-08-10 15:14:30.675557	Users experiencing login issues on mobile devices.	URGENT	david.brown@email.com	David Brown	PENDING	Bug Report: Login Issue	2025-08-10 15:14:30.675557
1585	Dark mode will be implemented in next release	Admin User	\N	FEATURE_REQUEST	2025-08-10 15:14:30.677339	Add dark mode option for better user experience.	LOW	sarah.wilson@email.com	Sarah Wilson	RESOLVED	Feature Request: Dark Mode	2025-08-10 15:14:30.677339
1586	Profile information corrected	Admin User	\N	USER_REPORT	2025-08-10 15:14:30.679437	User mike.johnson provided incorrect information on their profile.	MEDIUM	david.brown@email.com	David Brown	CLOSED	Profile Information	2025-08-10 15:14:30.679437
1587	Investigating server performance	Tech Lead	\N	SYSTEM_REPORT	2025-08-10 15:14:30.681426	Users reporting slow loading times during peak hours.	HIGH	system@ijaa.com	System Monitor	IN_PROGRESS	System Performance Issue	2025-08-10 15:14:30.681426
1588	\N	\N	\N	FEATURE_REQUEST	2025-08-10 15:14:30.682925	Add video calling feature for alumni networking.	MEDIUM	alex.chen@email.com	Alex Chen	PENDING	Feature Request: Video Calls	2025-08-10 15:14:30.682925
1589	Fake accounts removed and IP blocked	Admin User	\N	SECURITY_REPORT	2025-08-10 15:14:30.684126	Multiple fake accounts created with similar patterns.	HIGH	security@ijaa.com	Security Team	RESOLVED	Spam Account	2025-08-10 15:14:30.684126
1590	\N	\N	\N	BUG_REPORT	2025-08-10 15:14:30.685235	App crashes when accessing profile page on iOS devices.	URGENT	mobile@ijaa.com	Mobile User	PENDING	Mobile App Bug	2025-08-10 15:14:30.685235
1591	Working on screen reader support	UX Team	\N	FEATURE_REQUEST	2025-08-10 15:14:30.686351	Improve accessibility features for visually impaired users.	MEDIUM	accessibility@ijaa.com	Accessibility Advocate	IN_PROGRESS	Accessibility Request	2025-08-10 15:14:30.686351
1592	Privacy policy updated and communicated	Legal Team	\N	PRIVACY_REPORT	2025-08-10 15:14:30.687823	User concerned about data sharing practices.	LOW	privacy@ijaa.com	Privacy User	RESOLVED	Data Privacy Concern	2025-08-10 15:14:30.687823
1593	\N	\N	\N	BUG_REPORT	2025-08-10 15:14:30.68925	Users unable to register for upcoming events.	HIGH	events@ijaa.com	Event Coordinator	PENDING	Event Registration Issue	2025-08-10 15:14:30.68925
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.users (id, password, username, user_id, active) FROM stdin;
7	$2a$12$tBQKboN0E6fojUS.w/GdieuER4yecurGEttfEnSg3j10lzo6vnXBW	nusrat@gmail.com	ce6ceb99-edd2-4448-b85c-a85ad187540a	t
2	$2a$12$BCx8pF0cDIWEt7gh6BnpKOFtMonFkVL0I2VPVzphcz1UkFxTv7wvm	mdsahal.info@gmail.com	ce6ceb99-edd2-4448-b85c-a85ad187540e	t
6	$2a$12$s4DWWOuO0U2wWAI9Z5zjuec/8aorvGssloOUdMoor20b0LNU2EVty	tanvir@gmail.com	ce6ceb99-edd2-4448-b85c-a85ad187540b	t
5	$2a$12$PivPX2JgNXltTnJeVcj9R./VMIyg2UTJHb2MqzvBtf5b9r0jXBc.q	ayesha@gmail.com	ce6ceb99-edd2-4448-b85c-a85ad187540c	t
4	$2a$12$TbiMi3JvVxIooCwZLSnXje/pMyvOu0kNaRBdk2AZyMnL0dfEwIqDK	afrineva28@gmail.com	ce6ceb99-edd2-4448-b85c-a85ad187540d	t
9	$2a$12$6O/0xQyqCiuKRsWMlADwUOCmuh4OnpL7BlJeiB/nI98GGw1hIPK7e	testuser456	2d235b30-be17-4f66-8949-2c8c3065bb28	t
11	$2a$12$QqCtyrKXsxm4UPckzNE5e.F1Kg5A9HrE1WyXXoD6lWIquHjz.QZEO	testuser999	e68eff10-201a-4f4c-96d7-e5a227477720	t
12	$2a$12$Qc7RQ112XZudU.07yJdHTuEQGTPQUBeHrMAo1XGETC/0PN7frwL3m	testuser1000	4c78c4f8-2a7a-40f1-b2fd-587efb1c16b6	t
13	$2a$12$Z9No1R1va0ez3r.QyYqSs.2johjNZPGvaJzLuhlwJGdRk/miCmc8.	testuser1234	72d98c42-5ad1-4be5-9e52-a31ecb9c5d7f	t
8	$2a$12$QldFwO5Ehw352d22eEgpwOvbD93Z1Qzg7CPVO9u2y7rjBjNoUCcEm	testuser123	a52c4916-3f71-401a-98ba-9c1441b8afcf	f
15	$2a$12$CtS93Np9WqrROvPv.bTm/.Ftq7GIxNo2tbOybReR0t3pxxdr1S5me	testuser	74e90977-a050-4ef9-acc6-5d03cad34727	t
16	$2a$12$UdCxaovhbkLN/ecuD9g2wett2h9my/H4MwhM5VlGUST.g1xopVRXG	testuser2	db28f57a-019f-4667-a607-2d87000e4c52	t
17	$2a$12$Rxou9UBWEq5G0mUEEXWIteqTp3Cokf29YS5ivOlyGArYy73OnaecK	testuser3	c95bcb26-87ec-49be-8bc0-b23516f11b2d	t
18	$2a$12$aZnjGEswW65dpi03mCcHHOgk9cFqFv3IdvYO04zNPDNSJU7g0Zb8K	newuser123	87fa22ba-e390-4af9-abcd-894be751b943	t
19	$2a$12$TtxLTm6Ra10pzgBJENvmYO1lcTlaoLa6iQzw1EZwPy05TSQuyztPe	newuser456	88013526-81c3-4c7e-b464-5c684ac493f3	t
20	$2a$12$Ku7L9dJlVBH90RShsGJQ.up6FeqbTeFY8Sp90ErFjYuxTQHccENym	gatewayuser789	83cef4b6-7042-4f3d-8ab8-8c8219a744a4	t
21	$2a$12$YRCICWmJaCz1LAyE0lPl6eb49cRyCJppxpPBXMQAmITlx2EMbjveO	testuser4	012c7c13-3b50-4fa6-92db-be225ec5e29e	t
22	$2a$12$4wwlNYARqR6tqSBZO4I.N.8EYhQ/mKLDSKLZ83lGbIUSBcmU0uUGy	testuser@example.com	1b825f1a-9350-410a-bd81-dbd00544532a	t
\.


--
-- Name: admins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.admins_id_seq', 3, true);


--
-- Name: alumni_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.alumni_profiles_id_seq', 1, false);


--
-- Name: announcements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.announcements_id_seq', 1337, true);


--
-- Name: calendar_integrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.calendar_integrations_id_seq', 1, false);


--
-- Name: connections_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.connections_id_seq', 3, true);


--
-- Name: event_analytics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.event_analytics_id_seq', 174, true);


--
-- Name: event_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.event_comments_id_seq', 875, true);


--
-- Name: event_invitations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.event_invitations_id_seq', 527, true);


--
-- Name: event_media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.event_media_id_seq', 315, true);


--
-- Name: event_participations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.event_participations_id_seq', 879, true);


--
-- Name: event_reminders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.event_reminders_id_seq', 1, false);


--
-- Name: event_templates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.event_templates_id_seq', 219, true);


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.events_id_seq', 1181, true);


--
-- Name: experiences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.experiences_id_seq', 7, true);


--
-- Name: feature_flags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.feature_flags_id_seq', 1885, true);


--
-- Name: interests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.interests_id_seq', 4, true);


--
-- Name: profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.profiles_id_seq', 4, true);


--
-- Name: recurring_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.recurring_events_id_seq', 105, true);


--
-- Name: reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.reports_id_seq', 1593, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.users_id_seq', 22, true);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: alumni_profiles alumni_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.alumni_profiles
    ADD CONSTRAINT alumni_profiles_pkey PRIMARY KEY (id);


--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);


--
-- Name: calendar_integrations calendar_integrations_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.calendar_integrations
    ADD CONSTRAINT calendar_integrations_pkey PRIMARY KEY (id);


--
-- Name: connections connections_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.connections
    ADD CONSTRAINT connections_pkey PRIMARY KEY (id);


--
-- Name: event_analytics event_analytics_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_analytics
    ADD CONSTRAINT event_analytics_pkey PRIMARY KEY (id);


--
-- Name: event_comments event_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_comments
    ADD CONSTRAINT event_comments_pkey PRIMARY KEY (id);


--
-- Name: event_invitations event_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_invitations
    ADD CONSTRAINT event_invitations_pkey PRIMARY KEY (id);


--
-- Name: event_media event_media_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_media
    ADD CONSTRAINT event_media_pkey PRIMARY KEY (id);


--
-- Name: event_participations event_participations_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT event_participations_pkey PRIMARY KEY (id);


--
-- Name: event_reminders event_reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_reminders
    ADD CONSTRAINT event_reminders_pkey PRIMARY KEY (id);


--
-- Name: event_templates event_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_templates
    ADD CONSTRAINT event_templates_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: experiences experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (id);


--
-- Name: feature_flags feature_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT feature_flags_pkey PRIMARY KEY (id);


--
-- Name: interests interests_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.interests
    ADD CONSTRAINT interests_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);


--
-- Name: recurring_events recurring_events_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.recurring_events
    ADD CONSTRAINT recurring_events_pkey PRIMARY KEY (id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- Name: feature_flags uk2o4e6ne2aeiily8xlymvvydb8; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT uk2o4e6ne2aeiily8xlymvvydb8 UNIQUE (feature_name);


--
-- Name: event_invitations uk45yuxpmh9qgbbe7bw0t12247f; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_invitations
    ADD CONSTRAINT uk45yuxpmh9qgbbe7bw0t12247f UNIQUE (event_id, invited_username);


--
-- Name: admins uk47bvqemyk6vlm0w7crc3opdd4; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT uk47bvqemyk6vlm0w7crc3opdd4 UNIQUE (email);


--
-- Name: event_participations uk5yyep690fbvusroef09p22q05; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.event_participations
    ADD CONSTRAINT uk5yyep690fbvusroef09p22q05 UNIQUE (event_id, participant_username);


--
-- Name: alumni_profiles ukeujc7oc2vy9athxt589kf2bro; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.alumni_profiles
    ADD CONSTRAINT ukeujc7oc2vy9athxt589kf2bro UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_id_key UNIQUE (user_id);


--
-- Name: idx_connections_receiver; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_connections_receiver ON public.connections USING btree (receiver_username);


--
-- Name: idx_connections_requester; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_connections_requester ON public.connections USING btree (requester_username);


--
-- Name: idx_connections_status; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_connections_status ON public.connections USING btree (status);


--
-- Name: alumni_skills fki0f9txins73s8a7fkt3kxxxm2; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.alumni_skills
    ADD CONSTRAINT fki0f9txins73s8a7fkt3kxxxm2 FOREIGN KEY (alumni_id) REFERENCES public.alumni_profiles(id);


--
-- PostgreSQL database dump complete
--

