databases:
  - name: ijaa-user-db
    databaseName: ijaa_users
    user: ijaa_user
    plan: free
  - name: ijaa-event-db
    databaseName: ijaa_events
    user: ijaa_event
    plan: free
  - name: ijaa-file-db
    databaseName: ijaa_files
    user: ijaa_file
    plan: free

services:
  # Discovery Service (Eureka Server) - Must start first for service discovery
  - type: web
    name: ijaa-discovery-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: discovery-service/Dockerfile
    containerPort: 8761
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8761
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        value: false
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-discovery-service.onrender.com

  # Config Service - Must start second for configuration management
  - type: web
    name: ijaa-config-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: config-service/Dockerfile
    containerPort: 8888
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8888
      - key: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
        value: https://github.com/mesahal/ijaa.git
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-config-service.onrender.com

  # User Service - Core user management and authentication
  - type: web
    name: ijaa-user-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: user-service/Dockerfile
    containerPort: 8081
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        value: postgresql://ijaa_user:${ijaa-user-db.password}@${ijaa-user-db.host}:${ijaa-user-db.port}/ijaa_users
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-user-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 10
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: 30000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,info,metrics
      - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always

  # Event Service - Event management and advanced search
  - type: web
    name: ijaa-event-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: event-service/Dockerfile
    containerPort: 8082
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8082
      - key: SPRING_DATASOURCE_URL
        value: postgresql://ijaa_event:${ijaa-event-db.password}@${ijaa-event-db.host}:${ijaa-event-db.port}/ijaa_events
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-event-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 10
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: 30000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,info,metrics
      - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always

  # File Service - File upload and management
  - type: web
    name: ijaa-file-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: file-service/Dockerfile
    containerPort: 8083
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8083
      - key: SPRING_DATASOURCE_URL
        value: postgresql://ijaa_file:${ijaa-file-db.password}@${ijaa-file-db.host}:${ijaa-file-db.port}/ijaa_files
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-file-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 10
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: 30000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,info,metrics
      - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always
      - key: FILE_STORAGE_PATH
        value: /tmp/uploaded-files

  # Gateway Service - API Gateway and routing (must start last)
  - type: web
    name: ijaa-gateway-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: gateway-service/Dockerfile
    containerPort: 8080
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-gateway-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: USER_SERVICE_URL
        value: https://ijaa-user-service.onrender.com
      - key: EVENT_SERVICE_URL
        value: https://ijaa-event-service.onrender.com
      - key: FILE_SERVICE_URL
        value: https://ijaa-file-service.onrender.com
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,info,metrics
      - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always