databases:
  - name: ijaa-user-db
    databaseName: ijaa_users
    user: ijaa_user
    plan: free
  - name: ijaa-event-db
    databaseName: ijaa_events
    user: ijaa_event
    plan: free
  - name: ijaa-file-db
    databaseName: ijaa_files
    user: ijaa_file
    plan: free

services:
  # Discovery Service (Eureka Server) - Must start first for service discovery
  - type: web
    name: ijaa-discovery-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./discovery-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8761
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        value: false
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-discovery-service.onrender.com

  # Config Service - Must start second for configuration management
  - type: web
    name: ijaa-config-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./config-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8888
      - key: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
        value: https://github.com/mesahal/ijaa.git
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-config-service.onrender.com

  # User Service - Core user management and authentication
  - type: web
    name: ijaa-user-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./user-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2rk1ke3jp1c73fojn7g-a:5432/ijaa_users?sslmode=require&connectTimeout=30&socketTimeout=30
      - key: SPRING_DATASOURCE_USERNAME
        value: ijaa_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: pLnGRAeLWUTWTBHR5U3W1uWgfTVyyZBv
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-user-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 10
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: 30000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql
      - key: SPRING_SQL_INIT_CONTINUE_ON_ERROR
        value: true
      - key: SPRING_SQL_INIT_PLATFORM
        value: postgresql
      - key: SPRING_SQL_INIT_ENCODING
        value: UTF-8
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,info,metrics
      - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES
        value: true
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_BATCH_VERSIONED_DATA
        value: true
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE
        value: 20
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_FETCH_SIZE
        value: 20
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE
        value: UTC
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_PROVIDER_DISABLES_AUTOCOMMIT
        value: true
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS
        value: true

  # Event Service - Event management and advanced search
  - type: web
    name: ijaa-event-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./event-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8082
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2rk1km3jp1c73fojnjg-a:5432/ijaa_events?sslmode=require&connectTimeout=30&socketTimeout=30
      - key: SPRING_DATASOURCE_USERNAME
        value: ijaa_event
      - key: SPRING_DATASOURCE_PASSWORD
        value: vl1l3KLmSA01JD2rLOyCSBu78VEx2BZQ
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-event-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 10
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: 30000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,info,metrics
      - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always

  # File Service - File upload and management
  - type: web
    name: ijaa-file-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./file-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8083
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-file-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2rk1km3jp1c73fojnj0-a:5432/ijaa_files?sslmode=require&connectTimeout=30&socketTimeout=30
      - key: SPRING_DATASOURCE_USERNAME
        value: ijaa_file
      - key: SPRING_DATASOURCE_PASSWORD
        value: OOVLUeG4cx37CD6VtxqYsTdbgej0N8iX
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 10
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: 30000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: health,info,metrics
      - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always

  # Gateway Service - API Gateway and routing (must start last)
  - type: web
    name: ijaa-gateway-service
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./gateway-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-gateway-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
        value: user-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
        value: lb://ijaa-user-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
        value: Path=/ijaa/api/v1/user/**
      - key: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
        value: event-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
        value: lb://ijaa-event-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
        value: Path=/ijaa/api/v1/user/events/**
      - key: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
        value: file-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
        value: lb://ijaa-file-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
        value: Path=/ijaa/api/v1/users/**
      - key: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
        value: admin-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
        value: lb://ijaa-user-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
        value: Path=/ijaa/api/v1/admin/**
      - key: SPRING_CLOUD_GATEWAY_ROUTES_4_ID
        value: public-files
      - key: SPRING_CLOUD_GATEWAY_ROUTES_4_URI
        value: lb://ijaa-file-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_0
        value: Path=/ijaa/api/v1/events/*/banner/file/**
      - key: SPRING_CLOUD_GATEWAY_ROUTES_5_ID
        value: feature-flags
      - key: SPRING_CLOUD_GATEWAY_ROUTES_5_URI
        value: lb://ijaa-user-service
      - key: SPRING_CLOUD_GATEWAY_ROUTES_5_PREDICATES_0
        value: Path=/ijaa/api/v1/admin/feature-flags/*/enabled
