databases:
  - name: ijaa-postgres
    databaseName: ijaa_db
    user: ijaa_user
    plan: free

services:
  # Discovery Service (Eureka Server)
  - type: web
    name: ijaa-discovery-service
    env: java
    plan: free
    buildCommand: cd discovery-service && mvn clean package -DskipTests
    startCommand: cd discovery-service && java -jar target/discovery-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8761
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        value: false
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-discovery-service.onrender.com

  # Config Service
  - type: web
    name: ijaa-config-service
    env: java
    plan: free
    buildCommand: cd config-service && mvn clean package -DskipTests
    startCommand: cd config-service && java -jar target/config-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8888
      - key: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
        value: https://github.com/yourusername/ijaa.git
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-config-service.onrender.com

  # User Service
  - type: web
    name: ijaa-user-service
    env: java
    plan: free
    buildCommand: cd user-service && mvn clean package -DskipTests
    startCommand: cd user-service && java -jar target/user-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        value: postgresql://ijaa-postgres:5432/ijaa_db
      - key: SPRING_DATASOURCE_USERNAME
        value: ijaa_user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ijaa-postgres
          property: password
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-user-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql

  # Event Service
  - type: web
    name: ijaa-event-service
    env: java
    plan: free
    buildCommand: cd event-service && mvn clean package -DskipTests
    startCommand: cd event-service && java -jar target/event-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8082
      - key: SPRING_DATASOURCE_URL
        value: postgresql://ijaa-postgres:5432/ijaa_db
      - key: SPRING_DATASOURCE_USERNAME
        value: ijaa_user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ijaa-postgres
          property: password
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-event-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql

  # File Service
  - type: web
    name: ijaa-file-service
    env: java
    plan: free
    buildCommand: cd file-service && mvn clean package -DskipTests
    startCommand: cd file-service && java -jar target/file-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8083
      - key: SPRING_DATASOURCE_URL
        value: postgresql://ijaa-postgres:5432/ijaa_db
      - key: SPRING_DATASOURCE_USERNAME
        value: ijaa_user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ijaa-postgres
          property: password
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-file-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:db/schema.sql
      - key: SPRING_SQL_INIT_DATA_LOCATIONS
        value: classpath:db/data.sql
      - key: FILE_STORAGE_PATH
        value: /tmp/uploaded-files

  # Gateway Service
  - type: web
    name: ijaa-gateway-service
    env: java
    plan: free
    buildCommand: cd gateway-service && mvn clean package -DskipTests
    startCommand: cd gateway-service && java -jar target/gateway-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://ijaa-discovery-service.onrender.com/eureka/
      - key: EUREKA_INSTANCE_HOSTNAME
        value: ijaa-gateway-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: USER_SERVICE_URL
        value: https://ijaa-user-service.onrender.com
      - key: EVENT_SERVICE_URL
        value: https://ijaa-event-service.onrender.com
      - key: FILE_SERVICE_URL
        value: https://ijaa-file-service.onrender.com
