# IJAA Microservices Deployment Configuration for Render
# This file defines the deployment of all IJAA services on Render

# Database Service - PostgreSQL database
- type: pserv
  name: ijaa-db
  env: postgresql
  plan: free
  ipAllowList: []
  maxConnections: 100
  maintenanceWindow: sunday 00:00 UTC
  pgVersion: 15

# Discovery Service - Netflix Eureka Server (must start first)
- type: web
  name: ijaa-discovery-service
  env: docker
  plan: free
  autoDeploy: true
  dockerfilePath: ./discovery-service/Dockerfile
  envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod
    - key: SERVER_PORT
      value: 8761
    - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
      value: https://ijaa-discovery-service.onrender.com/eureka/
    - key: EUREKA_INSTANCE_HOSTNAME
      value: ijaa-discovery-service.onrender.com
    - key: JWT_SECRET
      generateValue: true

# Config Service - Spring Cloud Config Server (must start second)
- type: web
  name: ijaa-config-service
  env: docker
  plan: free
  autoDeploy: true
  dockerfilePath: ./config-service/Dockerfile
  envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod
    - key: SERVER_PORT
      value: 8888
    - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
      value: https://ijaa-discovery-service.onrender.com/eureka/
    - key: EUREKA_INSTANCE_HOSTNAME
      value: ijaa-config-service.onrender.com
    - key: JWT_SECRET
      generateValue: true

# User Service - User management and authentication
- type: web
  name: ijaa-user-service
  env: docker
  plan: free
  autoDeploy: true
  dockerfilePath: ./user-service/Dockerfile
  envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod
    - key: SERVER_PORT
      value: 8081
    - key: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://dpg-d2rk1km3jp1c73fojnjg-a:5432/ijaa_users?sslmode=require&connectTimeout=30&socketTimeout=30
    - key: SPRING_DATASOURCE_USERNAME
      value: ijaa_user
    - key: SPRING_DATASOURCE_PASSWORD
      value: pLnGRAeLWUTWTBHR5U3W1uWgfTVyyZBv
    - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: org.postgresql.Driver
    - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
      value: https://ijaa-discovery-service.onrender.com/eureka/
    - key: EUREKA_INSTANCE_HOSTNAME
      value: ijaa-user-service.onrender.com
    - key: JWT_SECRET
      generateValue: true
    - key: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - key: SPRING_JPA_SHOW_SQL
      value: false
    - key: SPRING_SQL_INIT_MODE
      value: always
    - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
      value: classpath:db/schema.sql
    - key: SPRING_SQL_INIT_DATA_LOCATIONS
      value: classpath:db/data.sql
    - key: SPRING_SQL_INIT_CONTINUE_ON_ERROR
      value: true
    - key: SPRING_SQL_INIT_PLATFORM
      value: postgresql
    - key: SPRING_SQL_INIT_ENCODING
      value: UTF-8
    - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: health,info,metrics
    - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
      value: always
    - key: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES
      value: true
    - key: SPRING_JPA_PROPERTIES_HIBERNATE_BATCH_VERSIONED_DATA
      value: true
    - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE
      value: 20
    - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_FETCH_SIZE
      value: 20
    - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE
      value: UTC
    - key: SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_PROVIDER_DISABLES_AUTOCOMMIT
      value: true
    - key: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS
      value: true
    - key: SPRINGDOC_SWAGGER_UI_SERVERS_0_URL
      value: https://ijaa-user-service.onrender.com
    - key: SPRINGDOC_SERVERS_0_URL
      value: https://ijaa-user-service.onrender.com
    - key: SPRINGDOC_API_DOCS_PATH
      value: /api-docs
    - key: SPRINGDOC_SWAGGER_UI_PATH
      value: /swagger-ui.html
    - key: SPRINGDOC_SWAGGER_UI_CONFIG_URL
      value: /api-docs/swagger-config
    - key: SPRINGDOC_SWAGGER_UI_URL
      value: /api-docs
    - key: PRODUCTION_SERVER_URL
      value: https://ijaa-user-service.onrender.com
    - key: SERVICE_HOSTNAME
      value: ijaa-user-service.onrender.com
    - key: SERVICE_PORT
      value: 8081

# Event Service - Event management and advanced search
- type: web
  name: ijaa-event-service
  env: docker
  plan: free
  autoDeploy: true
  dockerfilePath: ./event-service/Dockerfile
  envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod
    - key: SERVER_PORT
      value: 8082
    - key: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://dpg-d2rk1km3jp1c73fojnjg-a:5432/ijaa_events?sslmode=require&connectTimeout=30&socketTimeout=30
    - key: SPRING_DATASOURCE_USERNAME
      value: ijaa_event
    - key: SPRING_DATASOURCE_PASSWORD
      value: vl1l3KLmSA01JD2rLOyCSBu78VEx2BZQ
    - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: org.postgresql.Driver
    - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
      value: https://ijaa-discovery-service.onrender.com/eureka/
    - key: EUREKA_INSTANCE_HOSTNAME
      value: ijaa-event-service.onrender.com
    - key: JWT_SECRET
      generateValue: true
    - key: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - key: SPRING_JPA_SHOW_SQL
      value: false
    - key: SPRING_SQL_INIT_MODE
      value: always
    - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
      value: classpath:db/schema.sql
    - key: SPRING_SQL_INIT_DATA_LOCATIONS
      value: classpath:db/data.sql
    - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: health,info,metrics
    - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
      value: always
    - key: SPRINGDOC_SWAGGER_UI_SERVERS_0_URL
      value: https://ijaa-event-service.onrender.com
    - key: SPRINGDOC_SERVERS_0_URL
      value: https://ijaa-event-service.onrender.com
    - key: SPRINGDOC_API_DOCS_PATH
      value: /api-docs
    - key: SPRINGDOC_SWAGGER_UI_PATH
      value: /swagger-ui.html
    - key: SPRINGDOC_SWAGGER_UI_CONFIG_URL
      value: /api-docs/swagger-config
    - key: SPRINGDOC_SWAGGER_UI_URL
      value: /api-docs
    - key: PRODUCTION_SERVER_URL
      value: https://ijaa-event-service.onrender.com
    - key: SERVICE_HOSTNAME
      value: ijaa-event-service.onrender.com
    - key: SERVICE_PORT
      value: 8082

# File Service - File upload and management
- type: web
  name: ijaa-file-service
  env: docker
  plan: free
  autoDeploy: true
  dockerfilePath: ./file-service/Dockerfile
  envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod
    - key: SERVER_PORT
      value: 8083
    - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
      value: https://ijaa-discovery-service.onrender.com/eureka/
    - key: EUREKA_INSTANCE_HOSTNAME
      value: ijaa-file-service.onrender.com
    - key: JWT_SECRET
      generateValue: true
    - key: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://dpg-d2rk1km3jp1c73fojnj0-a:5432/ijaa_files?sslmode=require&connectTimeout=30&socketTimeout=30
    - key: SPRING_DATASOURCE_USERNAME
      value: ijaa_file
    - key: SPRING_DATASOURCE_PASSWORD
      value: OOVLUeG4cx37CD6VtxqYsTdbgej0N8iX
    - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: org.postgresql.Driver
    - key: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - key: SPRING_JPA_SHOW_SQL
      value: false
    - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: health,info,metrics
    - key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
      value: always
    - key: SPRINGDOC_SWAGGER_UI_SERVERS_0_URL
      value: https://ijaa-file-service.onrender.com
    - key: SPRINGDOC_SERVERS_0_URL
      value: https://ijaa-file-service.onrender.com
    - key: SPRINGDOC_API_DOCS_PATH
      value: /api-docs
    - key: SPRINGDOC_SWAGGER_UI_PATH
      value: /swagger-ui.html
    - key: SPRINGDOC_SWAGGER_UI_CONFIG_URL
      value: /api-docs/swagger-config
    - key: SPRINGDOC_SWAGGER_UI_URL
      value: /api-docs
    - key: PRODUCTION_SERVER_URL
      value: https://ijaa-file-service.onrender.com
    - key: SERVICE_HOSTNAME
      value: ijaa-file-service.onrender.com
    - key: SERVICE_PORT
      value: 8083

# Gateway Service - API Gateway and routing (must start last)
- type: web
  name: ijaa-gateway-service
  env: docker
  plan: free
  autoDeploy: true
  dockerfilePath: ./gateway-service/Dockerfile
  envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod
    - key: SERVER_PORT
      value: 8080
    - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
      value: https://ijaa-discovery-service.onrender.com/eureka/
    - key: EUREKA_INSTANCE_HOSTNAME
      value: ijaa-gateway-service.onrender.com
    - key: JWT_SECRET
      generateValue: true
    - key: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
      value: user-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
      value: lb://ijaa-user-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
      value: Path=/ijaa/api/v1/user/**
    - key: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
      value: event-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
      value: lb://ijaa-event-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
      value: Path=/ijaa/api/v1/user/events/**
    - key: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
      value: file-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
      value: lb://ijaa-file-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
      value: Path=/ijaa/api/v1/users/**
    - key: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
      value: admin-feature-flags
    - key: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
      value: lb://ijaa-user-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
      value: Path=/ijaa/api/v1/admin/feature-flags/**
    - key: SPRING_CLOUD_GATEWAY_ROUTES_4_ID
      value: admin-management
    - key: SPRING_CLOUD_GATEWAY_ROUTES_4_URI
      value: lb://ijaa-user-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_0
      value: Path=/ijaa/api/v1/admin/**
    - key: SPRING_CLOUD_GATEWAY_ROUTES_5_ID
      value: user-settings
    - key: SPRING_CLOUD_GATEWAY_ROUTES_5_URI
      value: lb://ijaa-user-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_5_PREDICATES_0
      value: Path=/ijaa/api/v1/user/settings/**
    - key: SPRING_CLOUD_GATEWAY_ROUTES_6_ID
      value: event-banner-files
    - key: SPRING_CLOUD_GATEWAY_ROUTES_6_URI
      value: lb://ijaa-file-service
    - key: SPRING_CLOUD_GATEWAY_ROUTES_6_PREDICATES_0
      value: Path=/ijaa/api/v1/events/**
    - key: SPRINGDOC_SERVERS_0_URL
      value: https://ijaa-gateway-service.onrender.com
    - key: SPRINGDOC_SWAGGER_UI_SERVERS_0_URL
      value: https://ijaa-gateway-service.onrender.com
    - key: SPRINGDOC_API_DOCS_PATH
      value: /v3/api-docs
    - key: SPRINGDOC_SWAGGER_UI_PATH
      value: /swagger-ui.html
    - key: SPRINGDOC_SWAGGER_UI_CONFIG_URL
      value: /v3/api-docs/swagger-config
    - key: SPRINGDOC_SWAGGER_UI_URL
      value: /v3/api-docs
    - key: PRODUCTION_SERVER_URL
      value: https://ijaa-gateway-service.onrender.com
    - key: SERVICE_HOSTNAME
      value: ijaa-gateway-service.onrender.com
    - key: SERVICE_PORT
      value: 8080
