server:
  port: 8081
  servlet:
    context-path: /ijaa
spring:
  security:
    user:
      name: sahal
      password: 123456
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sahal
    password: 123456
  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
