server:
  port: 8081
  servlet:
    context-path: /iija
spring:
  security:
    user:
      name: sahal
      password: 123456
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sahal
    password: 123456