spring:
  application:
    name: "gateway-service"
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://ijaa-user-service
          predicates:
            - Path=/ijaa/api/v1/user/**
          filters:
            - StripPrefix=0
        - id: event-service
          uri: lb://ijaa-event-service
          predicates:
            - Path=/ijaa/api/v1/user/events/**
          filters:
            - StripPrefix=0
        - id: file-service
          uri: lb://ijaa-file-service
          predicates:
            - Path=/ijaa/api/v1/users/**
          filters:
            - StripPrefix=0
        - id: admin-service
          uri: lb://ijaa-user-service
          predicates:
            - Path=/ijaa/api/v1/admin/**
          filters:
            - StripPrefix=0
        - id: public-files
          uri: lb://ijaa-file-service
          predicates:
            - Path=/ijaa/api/v1/events/*/banner/file/**
          filters:
            - StripPrefix=0
        - id: feature-flags
          uri: lb://ijaa-user-service
          predicates:
            - Path=/ijaa/api/v1/admin/feature-flags/*/enabled
          filters:
            - StripPrefix=0

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:16f7e412ee66030c3bf769281a076955f595be7479189c4e5ab1f90d2ae3c82e0c5170afcceba1e0f638648c01a468ff82b0723a970011f7fc0dd1a4ba70b0e1}

# CORS configuration
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
