spring:
  application:
    name: "gateway"
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ijaa_gateway}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:Admin@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB  # Allow large files to pass through gateway
      max-request-size: 100MB  # Allow multiple files in one request
      file-size-threshold: 1KB
      location: ${java.io.tmpdir}
      resolve-lazily: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: ${SERVER_PORT:8000}
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

# Add Swagger/OpenAPI configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway API
    # Set the correct base URL for production deployment
    servers:
      - url: ${PRODUCTION_SERVER_URL:http://localhost:8000}
        description: Production Server
  # Set the default server URL for API documentation
  servers:
    - url: ${PRODUCTION_SERVER_URL:http://localhost:8000}
      description: Production Server
  # Force the server URL in OpenAPI spec
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

info:
  app:
    name: "gatewayserver"
    description: "IJAA Gateway Server Application"
    version: "1.0.0"

jwt:
  secret: ${JWT_SECRET:16f7e412ee66030c3bf769281a076955f595be7479189c4e5ab1f90d2ae3c82e0c5170afcceba1e0f638648c01a468ff82b0723a970011f7fc0dd1a4ba70b0e1}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600}
