spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ijaa_files
    username: root
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true  # Explicitly enable multipart support
      max-file-size: 5MB
      max-request-size: 10MB  # Should be larger than max-file-size
      file-size-threshold: 1KB  # Files larger than this will be written to disk
      location: ${java.io.tmpdir}  # Temporary directory for multipart files
      resolve-lazily: false  # Resolve multipart files immediately
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8083
  # Add these for better file handling
  tomcat:
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# File storage configuration - FIXED PATHS
file:
  storage:
    # Use absolute path or create relative to project root
    base-path: ${user.home}/ijaa-uploads  # This will create uploads in user home directory
    # OR use: base-path: ./uploads  # For project relative path
    profile-photos-path: ${file.storage.base-path}/profile
    cover-photos-path: ${file.storage.base-path}/cover
    event-banners-path: ${file.storage.base-path}/event-banners
    allowed-image-types: jpg,jpeg,png,webp
    max-file-size-mb: 5

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Logging configuration
logging:
  level:
    com.ijaa.file_service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG  # Add multipart debugging
    org.springframework.web.servlet.mvc.method.annotation: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    # These help with file upload in Swagger UI
    supported-submit-methods: get,put,post,delete,options,head,patch,trace
    try-it-out-enabled: true
    # Add these for better file upload support in Swagger UI
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: com.ijaa.file_service.controller
