spring:
  application:
    name: file-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ijaa_files}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Admin@123}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true  # Explicitly enable multipart support
      max-file-size: 50MB  # Increased to match max-video-size-mb
      max-request-size: 100MB  # Should be larger than max-file-size for multiple files
      file-size-threshold: 1KB  # Files larger than this will be written to disk
      location: ${java.io.tmpdir}  # Temporary directory for multipart files
      resolve-lazily: false  # Resolve multipart files immediately
  web:
    resources:
      add-mappings: false  # Disable automatic static resource handling
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: ${SERVER_PORT:8083}

  # Add these for better file handling
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

# File storage configuration - FIXED PATHS
file:
  storage:
    # Use absolute path or create relative to project root
    base-path: ${user.home}/ijaa-uploads  # This will create uploads in user home directory
    # OR use: base-path: ./uploads  # For project relative path
    profile-photos-path: ${file.storage.base-path}/profile
    cover-photos-path: ${file.storage.base-path}/cover
    event-banners-path: ${file.storage.base-path}/event-banners
    event-post-media-path: ${file.storage.base-path}/event-posts
    allowed-image-types: jpg,jpeg,png,webp
    allowed-video-types: mp4,avi,mov,wmv,flv,webm
    max-file-size-mb: 5
    max-video-size-mb: 50

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Logging configuration
logging:
  level:
    com.ijaa.file_service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG  # Add multipart debugging
    org.springframework.web.servlet.mvc.method.annotation: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    # These help with file upload in Swagger UI
    supported-submit-methods: get,put,post,delete,options,head,patch,trace
    try-it-out-enabled: true
    # Add these for better file upload support in Swagger UI
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: com.ijaa.file.controller
  show-actuator: true
