spring:
  application:
    name: "user-service"
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: HikariPool-UserService
      leak-detection-threshold: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 20
          fetch_size: 20
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true
      platform: postgresql
      encoding: UTF-8

server:
  port: 8081

eureka:
  instance:
    preferIpAddress: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:16f7e412ee66030c3bf769281a076955f595be7479189c4e5ab1f90d2ae3c82e0c5170afcceba1e0f638648c01a468ff82b0723a970011f7fc0dd1a4ba70b0e1}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    config-url: /api-docs/swagger-config
    url: /api-docs
    servers:
      - url: https://ijaa-user-service.onrender.com
        description: Production Server
  servers:
    - url: https://ijaa-user-service.onrender.com
      description: Production Server
  packages-to-scan: com.ijaa.user.presenter.rest.api

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
