spring:
  application:
    name: "config-service"
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/mesahal/ijaa.git}
          default-label: main
          search-paths: config-service/src/main/resources/config
          clone-on-start: true

server:
  port: 8888

eureka:
  instance:
    preferIpAddress: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
