spring:
  application:
    name: "event-service"
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ijaa_events}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Admin@123}
    driver-class-name: org.postgresql.Driver
  cloud:
    compatibility-verifier:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB  # Allow large files for event posts
      max-request-size: 100MB  # Allow multiple files in one request
      file-size-threshold: 1KB
      location: ${java.io.tmpdir}
      resolve-lazily: false

  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: ${SERVER_PORT:8082}
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}


# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  packages-to-scan: com.ijaa.event.presenter.rest.api
  show-actuator: true

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      user-service-feature-flags:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      USER-SERVICE:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
